filepath: /Users/clinton/Development/gopath/src/github.com/cbegin/graven/project.yaml
name: github.com/cbegin/graven
version: 1.0.1
artifacts:
- classifier: win
  resources:
  - resources/commmon
  - resources/win
  targets:
  - executable: bin/gvn.exe
    package: .
    flags: ""
    env:
      GOARCH: amd64
      GOOS: windows
  archive: zip
- classifier: linux
  resources:
  - resources/commmon
  - resources/linux
  targets:
  - executable: bin/gvn
    package: .
    flags: ""
    env:
      GOARCH: amd64
      GOOS: linux
  archive: tar.gz
- classifier: darwin
  resources:
  - resources/commmon
  - resources/darwin
  targets:
  - executable: bin/gvn
    package: .
    flags: ""
    env:
      GOARCH: amd64
      GOOS: darwin
  archive: tgz
repositories:
- name: central
  url: http://foo.com/nexus
  username: me
  password: $password
  token: ""
  type: maven
- name: git
  url: http://github.com/api
  username: ""
  password: ""
  token: 32uoiew09u32jie93jioqu9oji21w
  type: github
