
name: github.com/cbegin/graven
version: 0.0.1-SNAPSHOT

artifacts:

  - classifier: win
    targets:
      - executable: gvn.exe
        package: .
        flags:
        env:
          GOOS: windows
          GOARCH: amd64
    resources:
      - resources/commmon
      - resources/win
    archive: zip

  - classifier: linux
    targets:
      - executable: gvn
        package: .
        flags:
        env:
          GOOS: linux
          GOARCH: amd64
    resources:
      - resources/commmon
      - resources/linux
    archive: tar.gz

  - classifier: darwin
    targets:
      - executable: gvn
        package: .
        flags:
        env:
          GOOS: darwin
          GOARCH: amd64
    resources:
      - resources/commmon
      - resources/darwin
    archive: tar.gz

repositories:

  - name: central
    url: http://foo.com/nexus
    username: me
    password: $password
    type: maven

  - name: git
    url: http://github.com/api
    token: 32uoiew09u32jie93jioqu9oji21w
    type: github
