name: github.com/org/myProject
version: 0.0.1
artifacts:
- classifier: darwin
  resources: []
  targets:
  - executable: bin/gvn
    package: .
    flags: ""
    env:
      GOARCH: amd64
      GOOS: darwin
  - executable: bin/hello 
    package: ./hello
    flags: ""
    env:
      GOARCH: amd64
      GOOS: darwin
  archive: tgz
- classifier: linux
  resources: []
  targets:
  - executable: bin/gvn
    package: .
    flags: ""
    env:
      GOARCH: amd64
      GOOS: linux
  - executable: bin/hello
    package: ./hello
    flags: ""
    env:
      GOARCH: amd64
      GOOS: linux
  archive: tar.gz
- classifier: win
  resources: []
  targets:
  - executable: gvn.exe
    package: .
    flags: ""
    env:
      GOARCH: amd64
      GOOS: windows
  - executable: hello.exe
    package: ./hello
    flags: ""
    env:
      GOARCH: amd64
      GOOS: windows
  archive: zip
repositories: []
