name: github.com/org/myProject
version: 0.0.1
artifacts:
- classifier: darwin
  resources: []
  targets:
  - executable: app0
    package: .
    flags: ""
    env:
      GOARCH: amd64
      GOOS: darwin
  - executable: app3
    package: ./hello
    flags: ""
    env:
      GOARCH: amd64
      GOOS: darwin
  archive: tgz
- classifier: linux
  resources: []
  targets:
  - executable: app0
    package: .
    flags: ""
    env:
      GOARCH: amd64
      GOOS: linux
  - executable: app3
    package: ./hello
    flags: ""
    env:
      GOARCH: amd64
      GOOS: linux
  archive: tar.gz
- classifier: win
  resources: []
  targets:
  - executable: app0.exe
    package: .
    flags: ""
    env:
      GOARCH: amd64
      GOOS: windows
  - executable: app3.exe
    package: ./hello
    flags: ""
    env:
      GOARCH: amd64
      GOOS: windows
  archive: zip
repositories: []
